### ISSUE TITLE
Add Vendor Dependencies for VictorSPX

### ISSUE THREAD

**Issue by fairmingos** [fairmingos/frc-2020#22]
We need to install the vendor dependencies for VictorSPX motor controllers

**Comment by johnwgillis** [comment]
Sorry for miscommunication, but this was already completed in previous meeting.

**Comment by steve-kaufman** [comment]
This issue is retrospective, for documentation purposes

**Comment by steve-kaufman** [comment]
The fix is to add a JSON blob called `Phoenix.json` from the vendor in a folder called `vendordeps`, which should already have `WPILibNewCommands.json` in it. This will automatically download the required dependencies in the build.gradle.

**Comment by johnwgillis** [comment]
Oh okay, there were two issues completed recently:
1) Updating the Victor SPX firmware using the Phoenix Tuner which isn’t a part of 
2) Updating the robot code to use the Phoenix library to drive with the Victor SPXs
